name: Copy Pushed File to 'log' Directory

on:
  push:
    branches:
      - main

jobs:
  copy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Copy Pushed File to 'log' Directory
      run: |
        mkdir -p log
        cp -r ${GITHUB_WORKSPACE}/${{ github.event.head_commit.added }} log/

    - name: Commit and Push Changes
      run: |
        git config --global user.name 'seyeon-k-k'
        git config --global user.email 'seyeon1121@naver.com'
        git add log/
        git commit -m "Copy pushed file to 'log' directory by GitHub Actions"
        git push
